version: "~> 1.0"
language: node_js
node_js:
    - 14
os:
    - osx
install:
    - npm install -g codecov
before_script:
    - npm install
script:
    - npm run build
after_success:
  - codecov
branches:
    only:
        - main
        - feature/codecov
