name: Build & Deploy
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
        ###### Remove until issue 26 is resolved. (https://github.com/HeyKos/nutshell.me/issues/26)
        # run: npm ci &&  npm run build && npm run test && npm run coverage && npm run build-storybook
        run: npm ci &&  npm run build && npm run test && npm run coverage
      - name: Update Test Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
      ###### Remove until issue 26 is resolved. (https://github.com/HeyKos/nutshell.me/issues/26)
      # - name: Publish Storybook
      #   uses: JamesIves/github-pages-deploy-action@3.6.2
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages # The branch the action should deploy to.
      #     FOLDER: docs-build # The folder that the build-storybook script generates files.
      #     CLEAN: true # Automatically remove deleted files from the deploy branch
      #     TARGET_FOLDER: docs # The folder that we serve our Storybook files from
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTSHELL_ME }}'
          channelId: live
          projectId: nutshell-me
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
