name: Build and Preview for Pull Request
'on': pull_request
jobs:
  build_and_preview:
    name: Build & Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
        run: npm ci && npm run build && npm run test && npm run coverage
      - name: Update Test Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
      - name: Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUTSHELL_ME }}'
          projectId: nutshell-me
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
